language: php
php:
  - '5.6'

before_install:
  # Create display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  # Install node packages.
  - npm install -g bower grunt-cli

  # Install Sass and Compass for Grunt to work.
  - gem install compass

  - bundler install
  - npm install
  - bower install
  - grunt serve > ~/grunt.log 2>&1 &

  # Install Behat
  - cd behat
  - cp behat.local.yml.travis behat.local.yml
  - composer install
  - cd ..

before_script:
  # Wait for Grunt to finish loading.
  - until $(curl --output /dev/null --silent --head --fail http://localhost:9000); do sleep 1; done

script:
  # Run behat tests.
  - cd behat
  - ./bin/behat --tags=~@wip
  - cat ~/grunt.log
